### ISSUE TITLE
please update this repo regarding to the main angularAMD

### ISSUE THREAD

**Issue by exp182** [marcoslin/bower-angularAMD#1]
When I install angularAMD with bower, it pulls an old version from this repo, which is lacks the dependencies i.e. the requireJS

**Comment by marcoslin** [comment]
The problem is that I cannot find a bower specific RequireJS dependency.  `bower install requirejs` will simply clone RequireJS project and you wont get the minified version from their download page.  There are few other repository that you can obtain the minified requrejs but these are not official ones.  Do you know of any RequireJS dependencies that we can rely on?

**Comment by marcoslin** [comment]
No response from user.  Closing the issue for now.
